### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by shamshadpattani** [GuilhE/android-quantity-picker-view#2]
Error Log : Attempt to invoke virtual method 'void com.github.guilhe.views.QuantityPickerView.setActionListener(com.github.guilhe.views.QuantityPickerView$QuantityPickerViewActionListener)' on a null object reference
       
my code: val listener = object : QuantityPickerView.QuantityPickerViewActionListener {
          override fun onValueChanged(view: QuantityPickerView, value: Int) {
            (view.parent as FrameLayout).elevation = if (value == view.min) dpToPx(0) else dpToPx(5)
          }
          override fun onToggleFinish(isOpen: Boolean) {}
          override fun beforeStartToggle(willOpen: Boolean) {}
        }

**Comment by GuilhE** [comment]
Hello @shamshadpattani you experienced this error while running the sample app?

**Comment by shamshadpattani** [comment]
Nop...I want to show this button when I click another button...the I hide the button it shows the error...

**Comment by shamshadpattani** [comment]
So simply my question is how to hide the button.

**Comment by GuilhE** [comment]
So this question is not related to this lib, it's a general Android question on how to show/hide a View given a certain logic, right?

Do you have any repo where this is implemented so I can take a look in the bigger picture?

**Comment by shamshadpattani** [comment]
I know how to hide it. BUT WHEN I HIDE THE PICKER..THE AFTER IT VISIIBILE IT SHOW  IT must not be null

**Comment by GuilhE** [comment]
First of all, calm down, I have no obligation of wasting my time with you, so, If I do, show some respect.

Again, I need more code. I use this lib in many projects that show/hide/animate/whatever, and I have no null pointer exceptions.
If you can't provide more code I'm not able to help you.
