### ISSUE TITLE
Animation getting slower on lower version android phone

### ISSUE THREAD

**Issue by iambharath07** [GuilhE/android-quantity-picker-view#4]
Animation is getting slower while opening and closing
My XML :

`<FrameLayout
            android:id="@+id/picker_parent"
            android:layout_width="160dp"
            android:layout_height="50dp"
            android:background="@drawable/white_rounded_bg"
            android:padding="5dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:layout_marginTop="@dimen/_2sdp"
            android:visibility="visible"
            app:layout_constraintTop_toBottomOf="@+id/priceLayout">

            <com.github.guilhe.views.QuantityPickerView
                android:id="@+id/picker"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                app:textLabelFont="@font/poppins_medium"
                app:textLabelFormatter="%s "
                app:textLabelSize="14sp"
                app:rippleColor="@color/white"
                app:btnAdd="@drawable/default_btn_add"
                app:btnRemove="@drawable/default_btn_remove"
                app:backgroundColor="@color/white"
                tools:isOpen="true" />
        </FrameLayout>`

Testing device : **Vivo V3** 
Version : **Android 5.1**
API Level : **21**

**Comment by GuilhE** [comment]
Hello @iambharath07 ,
Have you tried running the sample in your device and see if it gets slower too? I never experienced this problem, I have a grid layout full of `QuantityPickerViews` and they run smooth (at the same time).

**Comment by Bharath-D** [comment]
Thank you for your response. 
I ran it in the device(Android 5.1) itself not in the emulator. But it works perfectly in my Android 10 device.

**Comment by GuilhE** [comment]
I was asking If you've tested the sample app in your device (5.1) to check if the animation it's also slow.

When you say it works on your Android 10 device you're referring to your code or the sample app?

**Comment by Bharath-D** [comment]
The previous issue is with my device. Thank you. 
Actually I have another issue regarding the button. Do I need to create it as another issue or can I write here?
