### ISSUE TITLE
How to open quantity-picker view programmatically

### ISSUE THREAD

**Issue by Bharath-D** [GuilhE/android-quantity-picker-view#5]
First of all, thank you very much for your help in solving issues. I've just met with another issue.
How to open programmatically if there is any value
My XML :
`holder.getView(R.id.picker) as QuantityPickerView).apply {
        if(it.picker_count!=null){
          value=it.picker_count!!             
        }
      }` 
  //not working below line
          this.isOpen

**Comment by GuilhE** [comment]
Hello @Bharath-D I'm glad you find this lib helpful 😃 
Please consider giving me a "[star](https://github.com/GuilhE/android-quantity-picker-view/stargazers)" and/or "[buying me some coffee](https://www.buymeacoffee.com/GuilhE)".

Regarding your issue, please see [here](https://github.com/GuilhE/android-quantity-picker-view/issues/1#issuecomment-605302280).

Regards.

**Comment by Bharath-D** [comment]
Sorry, my issue is not solved. When, item selected is 1 or more the picker shows/open and the count is displayed. But, when count is zero i need it to  be closed/hidden.  But it is showing/open when it is zero. Is there any way to hide the count when it is zero?

**Comment by GuilhE** [comment]
Yes, you have an attribute for that: `<attr name="autoToggle" format="boolean" />` that will close the picker when `<attr name="min" format="integer" />` is reached.

**Comment by Bharath-D** [comment]
Sorry to say that the as per your direction
```
`(holder.getView(R.id.picker) as QuantityPickerView).apply {
          min=0
          max=it.max_qty
          if(it.picker_count != null) {
              value=it.picker_count!!
          } else {
              this.value=0
              this.isAutoToggleEnabled=false
          }
      }`
```
is not closing the picker
My XML:
```
`<com.github.guilhe.views.QuantityPickerView
                android:id="@+id/picker"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                app:textLabelFont="@font/poppins_medium"
                app:textLabelFormatter="%s "
                app:textLabelSize="14sp"
                app:rippleColor="@color/line"
                app:min="0"
                app:btnAdd="@drawable/ic_plus"
                app:isOpen="true"
                app:btnRemove="@drawable/ic_removes"
                app:backgroundColor="@color/line" />
```

![WhatsApp Image 2020-07-26 at 11 51 56 AM](https://user-images.githubusercontent.com/40658335/88473075-8df4c100-cf37-11ea-8f41-f5600ec4a5c6.jpeg)

**Comment by GuilhE** [comment]
Have you tried the sample app? It has this behaviour working as expected.
`isAutoToggleEnabled` it's true by default and `min` it's 0 by default, so you shouldn't need extra logic for that.

Can you explain please the logic you want to achieve with this:
```
(holder.getView(R.id.picker) as QuantityPickerView).apply {
          min=0
          max=it.max_qty
          if(it.picker_count != null) {
              value=it.picker_count!!
          } else {
              this.value=0
              this.isAutoToggleEnabled=false
          }
      }
```

**Comment by Bharath-D** [comment]
Sorry for the late reply
Sometimes value from server can be 0 or greater than 0 or maybe null. So if the value is 0 then the picker must be closed
Min = 0
Max = max value set from server
 then
if picker count is null then  the value from api call will be set as picker count value (it maybe 1 2 3etc)
if null then we set value = 0 and AutoToggle enable = false
I also tried
if value = 0 then IsAutoToggle enable = false

**Comment by GuilhE** [comment]
This kind of issues are not related to the lib itself, instead, to your app logic and misinterpretation of attributes logic.

A quick wrap up:

1. A picker will have `min = 0` and `IsAutoToggle = true` by **default**.
2. If you want to open/close picker you should use `toggle function`
3. If you want to hide a picker `view.visibility = View.GONE/INVISIBLE`
4. Using `app:isOpen="true"` will instantiate an open picker **regardless** of it's value

So, looking into your xml, you are setting `app:isOpen="true"` which will instantiate an open picker, even if value = 0. Remove that line.

Regards.

**Comment by Bharath-D** [comment]
Thank you for the help. It worked when I used the toggle. But it is not
showing the count.
I'll contribute Readme with toggle functions and others
