### ISSUE TITLE
Count is not displaying

### ISSUE THREAD

**Issue by Bharath-D** [GuilhE/android-quantity-picker-view#6]
Thank you for the help. It worked when I used the toggle. But it is not
showing the count.

![WhatsApp Image 2020-07-27 at 8 36 02 PM (1)](https://user-images.githubusercontent.com/40658335/88789347-47f86100-d1b4-11ea-8fbc-9888bd56a922.jpeg)

**Comment by GuilhE** [comment]
What are the values of `showLabel`, `textLabelFormatter` and `textLabelSize`? 
Put a break point [here](https://github.com/GuilhE/android-quantity-picker-view/blob/6a000ff666f34018763443c3e6f79791da0c7ef2/quantity-picker-view/src/main/java/com/github/guilhe/views/QuantityPickerView.kt#L495-L497): 
```
if (showLabel) {
    drawCenteredText(canvas, textLabelPaint.apply { alpha = labelAlpha }, String.format(textLabelFormatter, value))
}
```

And watch those values.

**Comment by Bharath-D** [comment]
```
<com.github.guilhe.views.QuantityPickerView
                android:id="@+id/picker"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                app:textLabelFont="@font/poppins_medium"
                app:textLabelSize="12sp"
                app:rippleColor="@color/line"
                app:min="0"
                android:visibility="visible"
                app:btnAdd="@drawable/ic_plus"
                app:btnRemove="@drawable/ic_removes"
                app:backgroundColor="@color/line"/>
```
```
(holder.getView(R.id.picker) as QuantityPickerView).apply {
          visibility=View.VISIBLE
          min=0
          max=it.stock
      if(it.picker_count != null) {
         value=it.picker_count!!
          toggle(500L,TimeInterpolator {
              2.5f
          })
          } else {
          value=0
          }
```
```
- ShowLabel is True. I checked by debugging.  
- Is it mandatory to add TextLabelFormat or  is it automatically added?
- I've also tried textLabelFormat=value.toString
 **Still no count is displaying**

**Comment by GuilhE** [comment]
> - Is it mandatory to add TextLabelFormat or  is it automatically added?

No, by default is `"%s"`

> - I've also tried textLabelFormat=value.toString

This won't work either, because of this: `String.format(textLabelFormatter, value)`, the `textLabelFormat` must be used with `String.format` therefore, only values like `"%s"` (default) `"%s unit"`, etc... will work.

I can't see what's missing here since I've never experienced this problem. You'll have to perform a more extensive debug and validate `onDraw()` is receiving the right parameters.
